#!/bin/bash

# splay - Play sound files over the amplifier

# Ring standard ringtone when called with no arguments
self=$(readlink -e $0) dir=${self%/*}
[[ $@ ]] && i="$@" || i="$dir/soundfiles/0.ring"
relaypin=26 ampdelay=1 shutoffdelay=.3 on=0 off=1

# For testing without gpio installed
gpio=$(type -p gpio) || gpio(){ :;}

# Turn on the amplifier, play the file, and turn if off again
gpio export $relaypin out
gpio -g write $relaypin $on
sleep $ampdelay
for f in "$i"
do [[ -f $f ]] && play -V0 -q "$f" ||
		echo "Argument is not a file: $f"
done
sleep $shutoffdelay
gpio -g write $relaypin $off

exit 0
